server:
    host: localhost
    port: 8080

db:
    host: localhost
    port: 3306
    user: user
    passwd: pass
    name: pikvm

query:
    ping: "SELECT version()"
    auth: "SELECT 1 FROM kvm_users WHERE username = %(user)s AND password = %(passwd)s AND kvmid = %(secret)s"

logging:
    version: 1
    disable_existing_loggers: false

    formatters:
        console:
            (): logging.Formatter
            style: "{"
            format: "{asctime} {name:30.30} {levelname:>7} --- {message}"

    handlers:
        console:
            level: DEBUG
            class: logging.StreamHandler
            stream: ext://sys.stdout
            formatter: console

    root:
        level: INFO
        handlers:
            - console
